server:
  port: 8084
spring:
  application:
    name: provider-user  # 项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:                       # 指定数据源
    platform: h2                    # 指定数据源类型
    schema: classpath:schema.sql    # 指定h2数据库的建表脚本
    data: classpath:data.sql        # 指定h2数据库的insert脚本


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30  # 用于定义服务续约任务的调用间隔时间，默认为30秒
    lease-expiration-duration-in-seconds: 90  # 定义服务失效的时间， 默认为90秒。
logging:
  level: info


