server:
  port: 8087
spring:
  application:
    name: consumer-movie-feign

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka


# 启用hystrix 断容器
#feign:
#  hystrix:
#    enabled: true