server:
  port: 8100

spring:
  application:
    name: api-gateway-filter

  mvc:
  # 出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
    throw-exception-if-no-handler-found: true
  # 不要为工程中的资源建立映射
  resources:
    add-mappings: false


eureka:
  client:
    service-url:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka     # 与eureka 通信
  instance:
    hostname: gataway
    # 下面整个树都是非必须的，如果不配置，将默认使用 http://GATEWAY:GATEWAY_PORT/想要访问的Eureka 服务id的小写， 路由到： http://想要访问的Eureka服务id 的小写：该服务多扣
# ===============================配置方式一===============================
#zuul:
#  routes:
#    movie:  # 随便写，在zuul 上面唯一即可； 这里的值 = service-id 时， service-id可以不写
#      path: /movie/**   # 想要映射的路径
#      serviceId: consumer-movie-ribbon   # eureka中的serviceId
#      #需要忽视的服务（配置后将不会路由）
#  ignored-services: provider-user
# ===============================配置方式二===============================

zuul:
  routes:
    consumer-movie-ribbon: movie/**
  ignored-services: provider-user



  # ===============================其他的一些规则===============================
  # 忽略表达式
  # ignored-patterns: /**/movie/**
  # 路由前缀
  prefix: /api
  #  对于代理前缀会默认从路径中移除，我们可以通过设置
  #  zuul.stripPrefix= false 来关闭该移除代理前缀的动作，也可以通过 zuul.routes. <route>.strip-prefix=true 来对指定路由关闭移除代理前缀的动作。
  strip-prefix: true

