server:
  port: 8763    #  指定该Eureka 端口

#spring:
##  profiles:
##    active: peer2
#  application:
#      name: eureka-server

logging:
  level: info

eureka:
  instance:
    hostname: peer2
#    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8762/eureka/

