server:
  port: 8086
spring:
  application:
    name: consumer-movie-ribbon

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka


